/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const _kFontPkg = null;

  static const IconData wb_sunny = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData air = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperatire = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wind = IconData(0xf72e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature_high = IconData(0xf769, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature_low = IconData(0xf76b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
